import { expect, test } from '@playwright/test';

test('10k-row MDI workspace starts promptly and stays virtualized', async ({ page }) => {
  const start = Date.now(); await page.goto('/?freeze=1'); await page.getByRole('complementary', { name: 'Tools' }).getByRole('button', { name: /Interfaces/ }).click(); await page.getByRole('region', { name: 'Interfaces' }).locator('.ou-grid-row').first().waitFor();
  const readyMs = Date.now() - start;
  const renderedRows = await page.getByRole('region', { name: 'Interfaces' }).locator('.ou-grid-row').count();
  expect(readyMs).toBeLessThan(3000);
  expect(renderedRows).toBeLessThan(60);
  const metrics = await page.evaluate(() => ({ resources: performance.getEntriesByType('resource').length, heap: (performance as Performance & { memory?: { usedJSHeapSize: number } }).memory?.usedJSHeapSize || null }));
  console.log(JSON.stringify({ readyMs, renderedRows, ...metrics }));
});

test('live focus, six-window load, 10k×20 grid and move/resize remain responsive', async ({ page }) => {
  await page.goto('/'); const launcher = page.getByRole('complementary', { name: 'Tools' }); await launcher.getByRole('button', { name: /Interfaces/ }).click(); const interfaces = page.getByRole('region', { name: 'Interfaces' }); await interfaces.locator('.ou-grid-row').first().dblclick(); const properties = page.getByRole('region', { name: /Properties/ }); await properties.getByRole('textbox', { name: 'Comment' }).focus(); const maxLiveFrameGap = await page.evaluate(() => new Promise<number>((resolve) => { const gaps: number[] = []; let previous = performance.now(); const end = previous + 2300; const frame = (now: number) => { gaps.push(now - previous); previous = now; if (now < end) requestAnimationFrame(frame); else resolve(Math.max(...gaps)); }; requestAnimationFrame(frame); })); await expect(properties.getByRole('textbox', { name: 'Comment' })).toBeFocused(); expect(maxLiveFrameGap).toBeLessThan(120); await page.keyboard.press('Escape');
  await launcher.getByRole('button', { name: /Routes/ }).click(); await launcher.getByRole('button', { name: /Firewall/ }).click(); await launcher.getByRole('button', { name: /^Log/ }).click(); await launcher.getByRole('button', { name: 'Users', exact: true }).click(); await page.getByRole('button', { name: 'View' }).click(); await page.getByRole('menuitem', { name: 'UI Gallery — Developer' }).click(); await expect(page.locator('.ou-mdi-window')).toHaveCount(6); const gallery = page.getByRole('region', { name: 'UI Gallery — Developer' }); await gallery.getByRole('button', { name: 'Maximize UI Gallery — Developer' }).click(); await gallery.locator('.ou-gallery').evaluate((element) => { element.scrollTop = element.scrollHeight; }); await gallery.getByRole('tab', { name: '20', exact: true }).click(); const wide = gallery.getByRole('grid', { name: '20 column stress grid' }); await expect(wide).toHaveAttribute('aria-rowcount', '10001'); expect(await wide.locator('.ou-grid-row').count()).toBeLessThan(60); await gallery.getByRole('button', { name: 'Restore UI Gallery — Developer' }).click();
  await launcher.getByRole('button', { name: /Interfaces/ }).click(); await page.evaluate(() => { (window as typeof window & { __ouLongTasks?: number[] }).__ouLongTasks = []; try { new PerformanceObserver((list) => (window as typeof window & { __ouLongTasks?: number[] }).__ouLongTasks?.push(...list.getEntries().map((entry) => entry.duration))).observe({ type: 'longtask' }); } catch { /* Long Task API is optional. */ } });
  const title = await interfaces.locator('.ou-window-titlebar').boundingBox(); if (!title) throw new Error('missing title'); await page.mouse.move(title.x + 100, title.y + 10); await page.mouse.down(); await page.mouse.move(title.x + 220, title.y + 70, { steps: 24 }); await page.mouse.up(); const handle = await interfaces.locator('.ou-window-resize-handle.is-se').boundingBox(); if (!handle) throw new Error('missing resize handle'); await page.mouse.move(handle.x + 3, handle.y + 3); await page.mouse.down(); await page.mouse.move(handle.x + 80, handle.y + 50, { steps: 16 }); await page.mouse.up(); const maxLongTask = await page.evaluate(() => Math.max(0, ...((window as typeof window & { __ouLongTasks?: number[] }).__ouLongTasks || []))); expect(maxLongTask).toBeLessThan(120);
  console.log(JSON.stringify({ sixWindowRows: await page.locator('.ou-grid-row').count(), wideRows: await wide.locator('.ou-grid-row').count(), maxLiveFrameGap, maxLongTask }));
});
