import { useState } from 'react';
import { CompactButton, CompactCheckbox, CompactComboBox, CompactRadio, CompactTabs, CompactTextField, PropertyRow, QuickFind, StateText, ToolbarButton16, ToolbarSeparator } from '../components/compact-controls';
import { DataGrid, type GridColumn } from '../components/DataGrid';
import { Dialog, EmptyState, LoadingState, Menu, MenuBar } from '../components/shell';
import { SplitView } from '../components/SplitView';
import { TreeView, type TreeNode } from '../components/TreeView';
import { makeInterfaces, type InterfaceRow } from './data';

const rows = makeInterfaces(100);
const columns: GridColumn<InterfaceRow>[] = [
  { key: 'name', label: 'Name', width: 160 }, { key: 'type', label: 'Type', width: 92 }, { key: 'status', label: 'Status', width: 94, render: (row) => <StateText state={row.status === 'Warning' ? 'warning' : row.status === 'Disabled' ? 'disabled' : 'active'}>{row.status}</StateText> }, { key: 'address', label: 'Address', width: 130 }, { key: 'rx', label: 'RX', width: 90, align: 'right' }, { key: 'tx', label: 'TX', width: 90, align: 'right' },
];
type StressRow = { id: string; [key: string]: string };
const stressRows: StressRow[] = Array.from({ length: 10000 }, (_, row) => Object.fromEntries([['id', `stress-${row}`], ...Array.from({ length: 25 }, (_, column) => [`c${column + 1}`, column % 4 === 0 ? String((row + 1) * (column + 7)) : `Value ${row + 1}.${column + 1}`])]) as StressRow);
const stressColumns: GridColumn<StressRow>[] = Array.from({ length: 25 }, (_, column) => ({ key: `c${column + 1}`, label: `Column ${String(column + 1).padStart(2, '0')}`, width: column % 4 === 0 ? 86 : 112, align: column % 4 === 0 ? 'right' : 'left' }));
const tree: TreeNode[] = [{ id: 'ip', label: 'IP', icon: 'network', children: [{ id: 'addresses', label: 'Addresses' }, { id: 'dhcp', label: 'DHCP Leases' }, { id: 'dns', label: 'DNS' }] }, { id: 'system', label: 'System', icon: 'settings', children: [{ id: 'users', label: 'Users' }, { id: 'resources', label: 'Resources' }] }];

export function Gallery() {
  const [tab, setTab] = useState('General'); const [dialog, setDialog] = useState(false); const [selectedTree, setSelectedTree] = useState('addresses'); const [query, setQuery] = useState('');
  const [wideCount, setWideCount] = useState('25');
  return <div className="ou-gallery">
    <section className="ou-showcase ou-span-2"><header><h2>Desktop commands</h2><span>Menu, toolbar, find, disabled and pressed states</span></header><MenuBar><Menu label="Object" items={[{ label: 'Add', shortcut: 'Ctrl+N' }, { label: 'Properties', shortcut: 'Alt+Enter' }, { type: 'separator' }, { label: 'Enabled', checked: true }, { label: 'Unavailable command', disabled: true }]} /><Menu label="View" items={[{ label: 'Details', checked: true }, { label: 'Category view' }]} /></MenuBar><div className="ou-local-toolbar"><ToolbarButton16 icon="add" label="Add" /><ToolbarButton16 icon="remove" label="Remove" disabled /><ToolbarSeparator /><ToolbarButton16 icon="enable" label="Enable" /><ToolbarButton16 icon="disable" label="Disable" /><ToolbarButton16 icon="refresh" label="Refresh" /><span className="ou-local-toolbar-fill" /><QuickFind value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Gallery find" /></div><div className="ou-demo-row"><CompactButton>Default</CompactButton><CompactButton className="is-default">Default action</CompactButton><CompactButton disabled>Disabled</CompactButton><StateText state="active">Connected</StateText><StateText state="warning">Degraded</StateText><StateText state="disabled">Disabled</StateText></div></section>

    <section className="ou-showcase"><header><h2>Compact fields</h2><span>22 px control contract</span></header><div className="ou-property-page"><PropertyRow label="Host"><CompactTextField defaultValue="core-gateway-01" /></PropertyRow><PropertyRow label="Port"><CompactTextField type="number" defaultValue="8291" /></PropertyRow><PropertyRow label="Mode"><CompactComboBox defaultValue="secure"><option value="secure">Secure</option><option>Legacy</option></CompactComboBox></PropertyRow><PropertyRow label="Password"><CompactTextField type="password" defaultValue="operator" /></PropertyRow><PropertyRow label="Options"><CompactCheckbox label="Connect automatically" defaultChecked /></PropertyRow><PropertyRow label="Access"><span><CompactRadio name="access" label="Write" defaultChecked /> <CompactRadio name="access" label="Read only" /></span></PropertyRow></div></section>

    <section className="ou-showcase"><header><h2>Property editor</h2><span>Tabs, read-only rows and actions</span></header><CompactTabs tabs={['General', 'Status', 'Traffic', 'Advanced']} active={tab} onChange={setTab} /><div className="ou-property-page"><PropertyRow label="Name"><CompactTextField defaultValue="ether1-uplink" /></PropertyRow><PropertyRow label="State"><StateText state="active">running</StateText></PropertyRow><PropertyRow label="MAC address">02:5A:91:6F:20:01</PropertyRow></div><div className="ou-property-actions"><CompactButton className="is-default" onClick={() => setDialog(true)}>Open modal</CompactButton><CompactButton>Apply</CompactButton></div></section>

    <section className="ou-showcase ou-span-2"><header><h2>Tree + table / table + detail</h2><span>Reusable SplitView composition</span></header><div className="ou-gallery-split"><SplitView first={<><TreeView nodes={tree} selected={selectedTree} onSelect={setSelectedTree} /><div className="ou-local-status"><span>{selectedTree}</span></div></>} second={<SplitView initial={64} min={42} first={<DataGrid rows={rows.slice(0, 24)} columns={columns} height={245} storageKey="gallery-split-grid" ariaLabel="Split view interfaces" />} second={<div className="ou-detail-pane"><strong>ether1-uplink</strong><PropertyRow label="Address">10.10.0.1/24</PropertyRow><PropertyRow label="State"><StateText state="active">running</StateText></PropertyRow><PropertyRow label="RX">152.2 KiB/s</PropertyRow></div>} />} /></div></section>

    <section className="ou-showcase ou-span-2"><header><h2>Wide DataGrid stress fixture</h2><span>6 / 12 / 20 / 25 columns · synchronized header</span></header><CompactTabs tabs={['6', '12', '20', '25']} active={wideCount} onChange={setWideCount} /><DataGrid rows={stressRows} columns={stressColumns.slice(0, Number(wideCount))} height={230} storageKey={`gallery-wide-${wideCount}`} ariaLabel={`${wideCount} column stress grid`} /><div className="ou-local-status"><span>10,000 rows</span><span>{wideCount} columns</span><span className="ou-local-status-fill" /><span>Virtualized · resize and scroll horizontally</span></div></section>

    <section className="ou-showcase"><header><h2>Loading and empty</h2><span>Compact tool-window feedback</span></header><LoadingState label="Reading configuration…" /><EmptyState title="No matching routes" description="Change the filter or add a static route." /></section>
    <section className="ou-showcase"><header><h2>Dialog patterns</h2><span>Focus trap, Escape and restoration</span></header><div className="ou-demo-row"><CompactButton onClick={() => setDialog(true)}>Property dialog</CompactButton><CompactButton disabled>Confirmation</CompactButton></div></section>
    <Dialog open={dialog} title="Interface Properties — ether1-uplink" onClose={() => setDialog(false)} onApply={() => setDialog(false)}><CompactTabs tabs={['General', 'Network', 'Status']} active={tab} onChange={setTab} /><div className="ou-property-page"><PropertyRow label="Name"><CompactTextField defaultValue="ether1-uplink" /></PropertyRow><PropertyRow label="Type"><CompactComboBox disabled defaultValue="Ethernet"><option>Ethernet</option></CompactComboBox></PropertyRow><PropertyRow label="Comment"><CompactTextField placeholder="Optional" /></PropertyRow><PropertyRow label="Enabled"><CompactCheckbox label="Enabled" defaultChecked /></PropertyRow></div></Dialog>
  </div>;
}
