import { useEffect, useMemo, useRef, useState, type MouseEvent, type PointerEvent as ReactPointerEvent, type ReactNode } from 'react';
import { ToolWindow } from './ToolWindow';
import type { ToolWindowState, WorkspaceMetrics } from './types';

type Manager = {
  state: { windows: Record<string, ToolWindowState>; order: string[]; activeId: string | null };
  setMetrics: (metrics: WorkspaceMetrics) => void; activateWindow: (id: string) => void; closeWindow: (id: string) => void; minimizeWindow: (id: string) => void; maximizeWindow: (id: string) => void; restoreWindow: (id: string) => void; setRect: (id: string, rect: ToolWindowState['rect']) => void;
};

export function MDIWorkspace({ manager, renderWindow }: { manager: Manager; renderWindow: (window: ToolWindowState) => ReactNode }) {
  const viewport = useRef<HTMLDivElement>(null);
  const [scroll, setScroll] = useState({ left: 0, top: 0, width: 1, height: 1, scrollWidth: 1, scrollHeight: 1 });
  const reportMetrics = () => { const element = viewport.current; if (element) { manager.setMetrics({ width: element.clientWidth, height: element.clientHeight, scrollLeft: element.scrollLeft, scrollTop: element.scrollTop }); setScroll({ left: element.scrollLeft, top: element.scrollTop, width: element.clientWidth, height: element.clientHeight, scrollWidth: element.scrollWidth, scrollHeight: element.scrollHeight }); } };
  useEffect(() => { const element = viewport.current; if (!element) return; const observer = new ResizeObserver(reportMetrics); observer.observe(element); reportMetrics(); return () => observer.disconnect(); }, []);
  const canvas = useMemo(() => Object.values(manager.state.windows).reduce((size, item) => ({ width: Math.max(size.width, item.rect.x + item.rect.width + 36), height: Math.max(size.height, item.rect.y + item.rect.height + 36) }), { width: 0, height: 0 }), [manager.state.windows]);
  useEffect(() => { const frame = requestAnimationFrame(reportMetrics); return () => cancelAnimationFrame(frame); }, [canvas.width, canvas.height]);
  const seek = (axis: 'horizontal' | 'vertical', event: MouseEvent<HTMLDivElement>) => { const element = viewport.current; if (!element) return; const box = event.currentTarget.getBoundingClientRect(); const ratio = axis === 'horizontal' ? (event.clientX - box.left) / box.width : (event.clientY - box.top) / box.height; if (axis === 'horizontal') element.scrollLeft = ratio * (element.scrollWidth - element.clientWidth); else element.scrollTop = ratio * (element.scrollHeight - element.clientHeight); };
  const keyboardScroll = (axis: 'horizontal' | 'vertical', event: React.KeyboardEvent) => { const element = viewport.current; if (!element) return; const current = axis === 'horizontal' ? element.scrollLeft : element.scrollTop; const viewportSize = axis === 'horizontal' ? element.clientWidth : element.clientHeight; const max = axis === 'horizontal' ? element.scrollWidth - element.clientWidth : element.scrollHeight - element.clientHeight; let next = current; if (event.key === 'Home') next = 0; else if (event.key === 'End') next = max; else if (event.key === 'PageUp') next -= viewportSize; else if (event.key === 'PageDown') next += viewportSize; else if ((axis === 'horizontal' && event.key === 'ArrowLeft') || (axis === 'vertical' && event.key === 'ArrowUp')) next -= 48; else if ((axis === 'horizontal' && event.key === 'ArrowRight') || (axis === 'vertical' && event.key === 'ArrowDown')) next += 48; else return; event.preventDefault(); if (axis === 'horizontal') element.scrollLeft = Math.max(0, Math.min(max, next)); else element.scrollTop = Math.max(0, Math.min(max, next)); };
  const beginThumbDrag = (axis: 'horizontal' | 'vertical', event: ReactPointerEvent<HTMLSpanElement>) => { event.preventDefault(); event.stopPropagation(); const element = viewport.current; if (!element) return; const startPointer = axis === 'horizontal' ? event.clientX : event.clientY; const startScroll = axis === 'horizontal' ? element.scrollLeft : element.scrollTop; const maxScroll = axis === 'horizontal' ? element.scrollWidth - element.clientWidth : element.scrollHeight - element.clientHeight; const track = event.currentTarget.parentElement?.getBoundingClientRect(); const thumb = event.currentTarget.getBoundingClientRect(); const travel = Math.max(1, axis === 'horizontal' ? (track?.width || 1) - thumb.width : (track?.height || 1) - thumb.height); const move = (moveEvent: PointerEvent) => { const pointer = axis === 'horizontal' ? moveEvent.clientX : moveEvent.clientY; const next = Math.max(0, Math.min(maxScroll, startScroll + (pointer - startPointer) / travel * maxScroll)); if (axis === 'horizontal') element.scrollLeft = next; else element.scrollTop = next; }; const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop); };
  const horizontalSize = Math.min(100, Math.max(12, scroll.width / scroll.scrollWidth * 100)); const verticalSize = Math.min(100, Math.max(12, scroll.height / scroll.scrollHeight * 100));
  const horizontalStart = (scroll.scrollWidth - scroll.width) > 0 ? scroll.left / (scroll.scrollWidth - scroll.width) * (100 - horizontalSize) : 0; const verticalStart = (scroll.scrollHeight - scroll.height) > 0 ? scroll.top / (scroll.scrollHeight - scroll.height) * (100 - verticalSize) : 0;
  return <div className="ou-mdi-frame"><div ref={viewport} className="ou-mdi-workspace" data-testid="mdi-workspace" onScroll={reportMetrics}><div className="ou-mdi-canvas" style={{ width: `max(100%, ${canvas.width}px)`, height: `max(100%, ${canvas.height}px)` }}>
    {manager.state.order.map((id, index) => { const item = manager.state.windows[id]; if (!item) return null; return <ToolWindow key={id} window={item} active={manager.state.activeId === id} zIndex={100 + index} onActivate={() => manager.activateWindow(id)} onClose={() => manager.closeWindow(id)} onMinimize={() => manager.minimizeWindow(id)} onMaximize={() => manager.maximizeWindow(id)} onRestore={() => manager.restoreWindow(id)} onRectChange={(rect) => manager.setRect(id, rect)}>{renderWindow(item)}</ToolWindow>; })}
  </div></div><div className="ou-mdi-scrollbar is-horizontal" role="scrollbar" aria-label="Workspace horizontal scroll" aria-orientation="horizontal" aria-valuemin={0} aria-valuemax={Math.max(0, scroll.scrollWidth - scroll.width)} aria-valuenow={scroll.left} tabIndex={0} onClick={(event) => seek('horizontal', event)} onKeyDown={(event) => keyboardScroll('horizontal', event)}><span style={{ width: `${horizontalSize}%`, left: `${horizontalStart}%` }} onPointerDown={(event) => beginThumbDrag('horizontal', event)} /></div><div className="ou-mdi-scrollbar is-vertical" role="scrollbar" aria-label="Workspace vertical scroll" aria-orientation="vertical" aria-valuemin={0} aria-valuemax={Math.max(0, scroll.scrollHeight - scroll.height)} aria-valuenow={scroll.top} tabIndex={0} onClick={(event) => seek('vertical', event)} onKeyDown={(event) => keyboardScroll('vertical', event)}><span style={{ height: `${verticalSize}%`, top: `${verticalStart}%` }} onPointerDown={(event) => beginThumbDrag('vertical', event)} /></div><div className="ou-mdi-scroll-corner" /></div>;
}
